import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const PdfService = {
    generateReport(report, transcript) {
        try {
            const doc = new jsPDF({
                orientation: 'p',
                unit: 'mm',
                format: 'a4',
                putOnlyUsedFonts: true
            });

            const margin = 15;
            const width = doc.internal.pageSize.getWidth();
            const height = doc.internal.pageSize.getHeight();

            // --- THEME CONFIG ---
            const isFire = report.mode === 'FIRE' || report.neris_data;

            // Professional Color Palette
            const theme = {
                primary: isFire ? [185, 28, 28] : [234, 88, 12], // Brand Color
                secondary: [51, 65, 85], // Slate-700
                text: {
                    dark: [15, 23, 42],
                    medium: [71, 85, 105],
                    light: [100, 116, 139]
                },
                bg: {
                    header: [248, 250, 252],
                    zebra: [241, 245, 249]
                },
                border: [226, 232, 240]
            };

            // --- HEADER ---
            const drawHeader = () => {
                // Top Brand Strip
                doc.setFillColor(...theme.primary);
                doc.rect(0, 0, width, 5, 'F');

                // Logo & Title
                doc.setFontSize(22);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(...theme.primary);
                doc.text("BEACON", margin, 20);

                const beaconWidth = doc.getTextWidth("BEACON");

                doc.setFont('helvetica', 'normal');
                doc.setTextColor(...theme.secondary);
                doc.text("SYSTEMS", margin + beaconWidth + 2, 20);

                doc.setFontSize(9);
                doc.setTextColor(...theme.text.light);
                doc.text("INTELLIGENT FIELD REPORTING", margin, 26);

                // Report ID Tag (Right Aligned)
                doc.setFontSize(10);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(...theme.text.dark);
                doc.text(isFire ? "FIRE INCIDENT REPORT" : "CLINICAL ENCOUNTER", width - margin, 18, { align: 'right' });

                doc.setFontSize(8);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(...theme.text.light);
                doc.text(`#${report.id || 'Unknown'} | ${new Date().toLocaleDateString()}`, width - margin, 24, { align: 'right' });

                // Bottom dividing line
                doc.setDrawColor(...theme.border);
                doc.setLineWidth(0.5);
                doc.line(margin, 30, width - margin, 30);
            };

            const drawFooter = (data) => {
                const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
                doc.setFontSize(8);
                doc.setTextColor(...theme.text.light);
                doc.text(`Confidential Record - Page ${data.pageNumber}`, margin, pageHeight - 10);
                doc.text("Generated by Beacon AI", width - margin, pageHeight - 10, { align: 'right' });
            };

            // --- CONTENT GENERATION ---

            // 1. Draw Header (Page 1 Only)
            drawHeader();

            let finalY = 35; // Start content here

            // 2. Executive Summary
            autoTable(doc, {
                startY: finalY,
                head: [['EXECUTIVE SUMMARY']],
                body: [[report.summary || "No summary available."]],
                theme: 'plain',
                headStyles: {
                    fillColor: theme.bg.header,
                    textColor: theme.primary,
                    fontSize: 10,
                    fontStyle: 'bold',
                    halign: 'left',
                    cellPadding: 3
                },
                bodyStyles: {
                    textColor: theme.text.dark,
                    fontSize: 10,
                    cellPadding: 5,
                    lineColor: theme.border,
                    lineWidth: 0.1
                },
                margin: { left: margin, right: margin }
            });
            finalY = doc.lastAutoTable.finalY + 10;

            // 3. Metadata Grid
            const metaBody = [
                ['DATE', new Date(report.timestamp).toLocaleDateString(), 'TIME', new Date(report.timestamp).toLocaleTimeString()],
                ['URGENCY', report.urgency || 'Normal', 'CATEGORY', report.category || 'General']
            ];

            autoTable(doc, {
                startY: finalY,
                head: [['INCIDENT METADATA', '', '', '']],
                body: metaBody,
                theme: 'grid',
                headStyles: {
                    fillColor: theme.secondary,
                    textColor: 255,
                    fontSize: 10,
                    fontStyle: 'bold',
                    halign: 'left'
                },
                bodyStyles: {
                    textColor: theme.text.dark,
                    fontSize: 9,
                    cellPadding: 4
                },
                columnStyles: {
                    0: { fontStyle: 'bold', cellWidth: 30, fillColor: theme.bg.zebra },
                    2: { fontStyle: 'bold', cellWidth: 30, fillColor: theme.bg.zebra }
                },
                styles: { lineColor: theme.border, lineWidth: 0.1 },
                margin: { left: margin, right: margin }
            });
            finalY = doc.lastAutoTable.finalY + 10;

            // 4. Domain Specific Details
            let domainBody = [];
            let domainTitle = "";

            if (isFire) {
                domainTitle = "FIRE INCIDENT DETAILS";
                if (report.neris_data) {
                    domainBody.push(['NERIS Type', report.neris_data.incident_type || '-']);
                    domainBody.push(['Property', report.neris_data.property_use || '-']);
                    domainBody.push(['Status', report.neris_data.stabilization_status || '-']);
                }
                if (report.scene_info) {
                    domainBody.push(['Building', report.scene_info.building || '-']);
                    domainBody.push(['Construction', report.scene_info.type || '-']);
                    domainBody.push(['Smoke', report.scene_info.smoke_conditions || '-']);
                    domainBody.push(['Fire', report.scene_info.flame_conditions || '-']);
                    domainBody.push(['Hazards', report.scene_info.exposures || 'None']);
                }
            } else {
                domainTitle = "PATIENT DEMOGRAPHICS";
                if (report.patient_info) {
                    domainBody.push(['Patient Name', report.patient_info.name || 'Unknown']);
                    domainBody.push(['Age / Sex', `${report.patient_info.age || '-'} / ${report.patient_info.sex || '-'}`]);
                    domainBody.push(['Mental Status', report.patient_info.mental_status || '-']);
                    domainBody.push(['Chief Complaint', report.patient_info.chief_complaint || 'N/A']);
                }
            }

            if (domainBody.length > 0) {
                autoTable(doc, {
                    startY: finalY,
                    head: [[domainTitle, '']],
                    body: domainBody,
                    theme: 'grid',
                    headStyles: {
                        fillColor: theme.secondary,
                        textColor: 255,
                        fontSize: 10,
                        fontStyle: 'bold'
                    },
                    columnStyles: {
                        0: { cellWidth: 40, fontStyle: 'bold', fillColor: theme.bg.zebra }
                    },
                    styles: { fontSize: 9, cellPadding: 3, lineColor: theme.border },
                    margin: { left: margin, right: margin }
                });
                finalY = doc.lastAutoTable.finalY + 10;
            }

            // 5. Timeline / Vitals
            if (isFire && report.timeline) {
                autoTable(doc, {
                    startY: finalY,
                    head: [['TIME', 'EVENT LOG']],
                    body: report.timeline.map(t => [t.time, t.event]),
                    theme: 'striped',
                    headStyles: { fillColor: theme.primary, textColor: 255, fontStyle: 'bold' },
                    columnStyles: { 0: { cellWidth: 30, fontStyle: 'bold' } },
                    styles: { fontSize: 9, cellPadding: 3 },
                    margin: { left: margin, right: margin }
                });
                finalY = doc.lastAutoTable.finalY + 10;
            }

            if (!isFire && report.vitals_timeline) {
                autoTable(doc, {
                    startY: finalY,
                    head: [['TIME', 'BP', 'HR', 'RR', 'SpO2', 'O2']],
                    body: report.vitals_timeline.map(v => [
                        v.time || '-', v.bp || '-', v.hr || '-', v.rr || '-', `${v.spo2}%`, v.o2 || '-'
                    ]),
                    theme: 'striped',
                    headStyles: { fillColor: theme.primary, textColor: 255, fontStyle: 'bold' },
                    styles: { fontSize: 9, halign: 'center' },
                    margin: { left: margin, right: margin }
                });
                finalY = doc.lastAutoTable.finalY + 10;
            }

            // 6. Hazards & Actions
            if (report.hazards && report.hazards.length > 0) {
                const hazardBody = report.hazards.map(h => [`(!) ${h}`]);
                autoTable(doc, {
                    startY: finalY,
                    head: [['SAFETY HAZARDS']],
                    body: hazardBody,
                    theme: 'grid',
                    headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: 'bold' },
                    bodyStyles: { textColor: [185, 28, 28], fontStyle: 'bold', fillColor: [254, 242, 242] },
                    margin: { left: margin, right: margin }
                });
                finalY = doc.lastAutoTable.finalY + 10;
            }

            if (report.action_items && report.action_items.length > 0) {
                const actionBody = report.action_items.map(a => [`[ ]  ${a}`]);
                autoTable(doc, {
                    startY: finalY,
                    head: [['RECOMMENDED ACTIONS']],
                    body: actionBody,
                    theme: 'grid',
                    headStyles: { fillColor: theme.secondary, textColor: 255 },
                    bodyStyles: { textColor: theme.text.dark },
                    margin: { left: margin, right: margin }
                });
                finalY = doc.lastAutoTable.finalY + 10;
            }

            // 7. Transcript
            if (transcript) {
                autoTable(doc, {
                    startY: finalY,
                    head: [['TRANSCRIPT RECORD']],
                    body: [[transcript]],
                    theme: 'plain',
                    headStyles: { fillColor: theme.bg.header, textColor: theme.text.medium, fontStyle: 'bold' },
                    bodyStyles: { textColor: theme.text.medium, fontSize: 8, font: 'courier' },
                    margin: { left: margin, right: margin }
                });
            }

            // Apply Headers/Footers
            const pageCount = doc.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);

                // Header: Page 1 only (already drawn, but good to be explicit in loop logic if we needed to clear)
                // Footer: All Pages
                drawFooter({ pageNumber: i });
            }

            doc.save(`Beacon_Report_${report.id}.pdf`);

        } catch (e) {
            console.error(e);
            alert("PDF Error: " + e.message);
        }
    }
};
