import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export const PdfService = {
    generateReport(report, transcript) {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        let yPos = 20;

        // --- Helpers ---
        const checkPageBreak = (heightNeeded) => {
            if (yPos + heightNeeded > pageHeight - margin - 20) { // Extra space for footer
                addFooter();
                doc.addPage();
                addHeader();
                yPos = 40; // Start below header
                return true;
            }
            return false;
        };

        const addHeader = () => {
            doc.setFillColor(249, 115, 22); // Orange primary
            doc.rect(0, 0, pageWidth, 5, 'F'); // Top colored bar

            doc.setFontSize(18);
            doc.setTextColor(30);
            doc.setFont("helvetica", "bold");
            doc.text("EMS FIELD REPORT", margin, 20);

            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.setFont("helvetica", "normal");
            doc.text("CONFIDENTIAL MEDICAL RECORD", pageWidth - margin, 20, { align: 'right' });

            doc.setDrawColor(200);
            doc.line(margin, 25, pageWidth - margin, 25);
        };

        const addFooter = () => {
            const totalPages = doc.internal.getNumberOfPages();
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
            doc.text(`Generated by Field Agent AI • ${new Date().toLocaleString()}`, margin, pageHeight - 10);
        };

        // --- Document Start ---
        addHeader();
        yPos = 35;

        // Meta Info Grid
        doc.setFillColor(245, 247, 250);
        doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 25, 2, 2, 'F');

        doc.setFontSize(10);
        doc.setTextColor(80);
        doc.text("DATE & TIME", margin + 5, yPos + 8);
        doc.text("CATEGORY", margin + 60, yPos + 8);
        doc.text("URGENCY", margin + 120, yPos + 8);

        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text(new Date(report.timestamp).toLocaleString(), margin + 5, yPos + 16);
        doc.text(report.category || 'General', margin + 60, yPos + 16);

        // Urgency Color
        if (report.urgency?.toLowerCase() === 'high') doc.setTextColor(220, 38, 38);
        else if (report.urgency?.toLowerCase() === 'medium') doc.setTextColor(234, 88, 12);
        else doc.setTextColor(22, 163, 74);

        doc.text((report.urgency || 'Normal').toUpperCase(), margin + 120, yPos + 16);

        yPos += 35;

        // Clinical Summary
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.setFont("times", "bold"); // Serif for section headers
        doc.text("Clinical Summary", margin, yPos);
        yPos += 8;

        doc.setFontSize(11);
        doc.setTextColor(50);
        doc.setFont("helvetica", "normal");
        const summaryLines = doc.splitTextToSize(report.summary || '', pageWidth - (margin * 2));
        doc.text(summaryLines, margin, yPos);
        yPos += (summaryLines.length * 6) + 10;

        // Structured Fields (Patient Info)
        if (report.structured_fields) {
            checkPageBreak(40);
            doc.setFontSize(14);
            doc.setTextColor(0);
            doc.setFont("times", "bold");
            doc.text("Patient Information", margin, yPos);
            yPos += 8;

            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");

            let xOffset = margin;
            Object.entries(report.structured_fields).forEach(([section, fields]) => {
                doc.setFont(undefined, 'bold');
                doc.text(section, xOffset, yPos);
                let localY = yPos + 6;
                doc.setFont(undefined, 'normal');

                Object.entries(fields).forEach(([key, value]) => {
                    doc.setTextColor(100);
                    doc.text(`${key}:`, xOffset, localY);
                    doc.setTextColor(0);
                    doc.text(`${value}`, xOffset + 35, localY);
                    localY += 6;
                });
                // Move to next column roughly
                // For simplicity in this version, we just stack if it gets too complex, but let's try a simple stack for now to be safe
                yPos = localY + 5;
            });
            yPos += 5;
        }

        // Vitals Timeline Table
        if (report.vitals_timeline) {
            checkPageBreak(60);
            doc.setFontSize(14);
            doc.setFont("times", "bold");
            doc.text("Vitals Log", margin, yPos);
            yPos += 5;

            autoTable(doc, {
                startY: yPos,
                head: [['Time', 'BP', 'HR', 'RR', 'SpO2', 'O2 Route']],
                body: report.vitals_timeline.map(r => [r.time, r.bp, r.hr, r.rr, r.spo2, r.o2]),
                theme: 'grid',
                headStyles: { fillColor: [249, 115, 22], textColor: 255, fontStyle: 'bold' },
                styles: { fontSize: 10, cellPadding: 3 },
                alternateRowStyles: { fillColor: [245, 247, 250] },
                margin: { left: margin, right: margin }
            });
            yPos = doc.lastAutoTable.finalY + 15;
        }

        // Interventions Table
        if (report.interventions_timeline) {
            checkPageBreak(60);
            doc.setFontSize(14);
            doc.setFont("times", "bold");
            doc.text("Interventions", margin, yPos);
            yPos += 5;

            autoTable(doc, {
                startY: yPos,
                head: [['Time', 'Intervention', 'Dose / Notes']],
                body: report.interventions_timeline.map(r => [r.time, r.intervention, r.dose]),
                theme: 'grid',
                headStyles: { fillColor: [51, 65, 85], textColor: 255 },
                styles: { fontSize: 10, cellPadding: 3 },
                margin: { left: margin, right: margin }
            });
            yPos = doc.lastAutoTable.finalY + 15;
        }

        // Assessment & OPQRST
        if (report.assessment) {
            checkPageBreak(60);
            doc.setFontSize(14);
            doc.setFont("times", "bold");
            doc.text("Clinical Assessment", margin, yPos);
            yPos += 8;

            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            Object.entries(report.assessment).forEach(([key, value]) => {
                checkPageBreak(20);
                doc.setFont(undefined, 'bold');
                doc.text(key + ":", margin, yPos);
                doc.setFont(undefined, 'normal');
                const lines = doc.splitTextToSize(value, pageWidth - margin - 50);
                doc.text(lines, margin + 35, yPos);
                yPos += (lines.length * 5) + 4;
            });
            yPos += 10;
        }

        // MIST & Narrative
        if (report.mist || report.narrative) {
            checkPageBreak(60);
            doc.setFontSize(14);
            doc.setFont("times", "bold");
            doc.text("Narrative & Handoff", margin, yPos);
            yPos += 8;

            if (report.mist) {
                doc.setFontSize(10);
                Object.entries(report.mist).forEach(([key, value]) => {
                    checkPageBreak(20);
                    doc.setFont(undefined, 'bold');
                    doc.text(key, margin, yPos);
                    yPos += 5;
                    doc.setFont(undefined, 'normal');
                    const lines = doc.splitTextToSize(value, pageWidth - (margin * 2));
                    doc.text(lines, margin + 5, yPos);
                    yPos += (lines.length * 5) + 4;
                });
                yPos += 5;
            }

            if (report.narrative) {
                checkPageBreak(40);
                doc.setFont(undefined, 'bold');
                doc.text("Full Narrative:", margin, yPos);
                yPos += 6;
                doc.setFont(undefined, 'normal');
                const lines = doc.splitTextToSize(report.narrative, pageWidth - (margin * 2));
                doc.text(lines, margin, yPos);
                yPos += (lines.length * 5) + 10;
            }
        }

        // Action Items
        if (report.action_items) {
            checkPageBreak(50);
            doc.setFontSize(14);
            doc.setFont("times", "bold");
            doc.text("Action Items", margin, yPos);
            yPos += 8;
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            report.action_items.forEach(item => {
                checkPageBreak(10);
                doc.text(`[ ] ${item}`, margin, yPos);
                yPos += 6;
            });
            yPos += 10;
        }

        // Add Footer to first page
        addFooter();

        // Transcript (New Page)
        const finalTranscript = report.original_transcript || transcript;
        if (finalTranscript) {
            doc.addPage();
            addHeader();
            yPos = 40;
            doc.setFontSize(14);
            doc.setFont("times", "bold");
            doc.text("Original Transcript", margin, yPos);
            yPos += 10;
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.setFont("helvetica", "normal");
            const transcriptLines = doc.splitTextToSize(finalTranscript, pageWidth - (margin * 2));
            doc.text(transcriptLines, margin, yPos);
            addFooter();
        }

        doc.save(`EMS_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
    }
};
